name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_AUTH_TYPE: pat
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle validate -t dev
      - run: databricks bundle deploy -t dev
      - run: databricks bundle run -t dev sample_job

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    env:
      DATABRICKS_AUTH_TYPE: pat
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle validate -t prod
      - run: databricks bundle deploy -t prod
      - run: databricks bundle run -t prod sample_job